### ISSUE TITLE
[need help] is this needed with DataClient?

### ISSUE THREAD

**Issue by MZorzy** [TrakHound/Fanuc-MTConnect-Agent#2]
is this Agent needed or already included on DataServer + DataClient ?

**Comment by PatrickRitchie** [comment]
Yes you would need to install this MTConnect Agent+Adapter separately from the TrakHound DataServer & DataClient. At some point we may include this in a comprehensive package but for now we are keeping the TrakHound applications separate from the MTConnect applications so that both are more flexible.
